language: node_js
node_js:
  - 15

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script: bash travis_script.sh "$DOCKER_USERNAME"

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME"/udagram-feed:version3
  - docker push "$DOCKER_USERNAME"/udagram-user:version2
  - docker push "$DOCKER_USERNAME"/udagram-frontend:version2
  - docker push "$DOCKER_USERNAME"/udagram-proxy:version2